<?php
return [
    'ccaa' => [
        'Andalucía',
        'Aragón',
        'Asturias',
        'Baleares',
        'Canarias',
        'Cantabria',
        'Castilla-La Mancha',
        'Castilla y León',
        'Cataluña',
        'Comunidad Valenciana',
        'Extremadura',
        'Galicia',
        'Madrid',
        'Murcia',
        'Navarra',
        'País Vasco',
        'La Rioja',
        'Ceuta',
        'Melilla'
    ],

    'provincias' => [
        'Álava',
        'Albacete',
        'Alicante',
        'Almería',
        'Asturias',
        'Ávila',
        'Badajoz',
        'Baleares',
        'Barcelona',
        'Burgos',
        'Cáceres',
        'Cádiz',
        'Cantabria',
        'Castellón',
        'Ceuta',
        'Ciudad Real',
        'Córdoba',
        'Cuenca',
        'Girona',
        'Granada',
        'Guadalajara',
        'Gipuzkoa',
        'Huelva',
        'Huesca',
        'Jaén',
        'A Coruña',
        'La Rioja',
        'Las Palmas',
        'León',
        'Lleida',
        'Lugo',
        'Madrid',
        'Málaga',
        'Melilla',
        'Murcia',
        'Navarra',
        'Ourense',
        'Palencia',
        'Pontevedra',
        'Salamanca',
        'Segovia',
        'Sevilla',
        'Soria',
        'Tarragona',
        'Tenerife',
        'Teruel',
        'Toledo',
        'Valencia',
        'Valladolid',
        'Bizkaia',
        'Zamora',
        'Zaragoza'
    ],
    'dni' => [
        'DNI',
        'NIE',
        'Pasaporte',
        'Otros'
    ],
    'sexo' => [
        'Hombre',
        'Mujer',
        'Otro'
    ],
];
