<?php
return [
    'ccaa' => [
        'Andalucía',
        'Aragón',
        'Canarias',
        'Cantabria',
        'Castilla y León',
        'Castilla-La Mancha',
        'Cataluña/Catalunya',
        'Ciudad Autónoma de Ceuta',
        'Ciudad Autónoma de Melilla',
        'Comunidad Foral de Navarra',
        'Comunidad de Madrid',
        'Comunitat Valenciana',
        'Extremadura',
        'Galicia',
        'Illes Balears',
        'La Rioja',
        'País Vasco/Euskadi',
        'Principado de Asturias',
        'Región de Murcia'
    ],

    'provincias' => [
        'Ávila',
        'A Coruña',
        'Alacant/Alicante',
        'Albacete',
        'Almería',
        'Araba/Álava',
        'Asturias',
        'Badajoz',
        'Barcelona',
        'Bizkaia',
        'Burgos',
        'Cáceres',
        'Cádiz',
        'Córdoba',
        'Cantabria',
        'Castelló/Castellón',
        'Ceuta',
        'Ciudad Real',
        'Cuenca',
        'Gipuzkoa',
        'Girona',
        'Granada',
        'Guadalajara',
        'Huelva',
        'Huesca',
        'Illes Balears',
        'Jaén',
        'La Rioja',
        'Las Palmas',
        'León',
        'Lleida',
        'Lugo',
        'Málaga',
        'Madrid',
        'Melilla',
        'Murcia',
        'Navarra',
        'Ourense',
        'Palencia',
        'Pontevedra',
        'Salamanca',
        'Santa Cruz de Tenerife',
        'Segovia',
        'Sevilla',
        'Soria',
        'Tarragona',
        'Teruel',
        'Toledo',
        'València/Valencia',
        'Valladolid',
        'Zamora',
        'Zaragoza'
    ],

    'actividad' => [
        'A. - Agricultura, ganadería, silvicultura y pesca',
        'B. - Industrias extractivas',
        'C. - Industria manufacturera',
        'D. - Suministro de energía eléctrica, gas, vapor y aire acondicionado',
        'E. - Suministro de agua, actividades de saneamiento, gestión de residuos y descontaminación',
        'F. - Construcción',
        'G. - Comercio al por mayor y al por menor',
        'H. - Transporte y almacenamiento',
        'I. - Hostelería',
        'J. - Información y comunicaciones',
        'K. - Actividades financieras y de seguros',
        'L. - Actividades inmobiliarias',
        'M. - Actividades profesionales, científicas y técnicas',
        'N. - Actividades administrativas y servicios auxiliares',
        'O. - Administración Pública y defensa; Seguridad Social obligatoria',
        'P. - Educación',
        'Q. - Actividades sanitarias y de servicios sociales',
        'R. - Actividades artísticas, recreativas y de entretenimiento',
        'S. - Otros servicios',
        'T. - Actividades de los hogares como empleadores de personal doméstico',
        'U. - Actividades de organizaciones y organismos extraterritoriales'
    ],

    'dni' => [
        'DNI',
        'NIE',
        'Pasaporte',
        'Otros'
    ],

    'sexo' => [
        'Hombre',
        'Mujer',
        'Otro'
    ],

    'idiomas' => [
        'Inglés',
        'Francés',
        'Otro idioma'
    ],

    'niveles_oficiales' => [
        'A1',
        'A2',
        'B1',
        'B2',
        'C1',
        'C2'
    ],

    'niveles_no_oficiales' => [
        'Básico',
        'Medio',
        'Avanzado'
    ],
    'situacion_laboral' => [
        'desempleado' => 'Trabajador/a desempleado/a',
        'ocupado' => 'Trabajador/a ocupado/a',
    ],

    // Categorías (checkboxes)
    'categorias' => [
        'categoria_direccion' => 'Dirección',
        'categoria_administracion' => 'Administración',
        'categoria_comercial' => 'Comercial',
        'categoria_mantenimiento' => 'Mantenimiento',
        'categoria_produccion' => 'Producción',
        'categoria_mando_intermedio' => 'Mando Intermedio',
        'categoria_tecnico' => 'Técnico/a',
        'trabajador_cualificado' => 'Trabajador/a cualificado/a',
        'trabajador_no_cualificado' => 'Trabajador/a de baja cualificación',
    ],

    // Situación desempleado (checkboxes)
    'situacion_desempleado' => [
        'demandante_empleo1' => 'Demandantes de primer empleo',
        'no_prestacion' => 'En paro sin prestación o subsidio',
        'subsidio_desempleo' => 'Percibe subsidio por desempleo',
        'prestacion_desempleo' => 'Percibe prestación por desempleo',
        'otros' => 'Otros no parados/as',
    ],

    'regimen_cotizacion' => [
        'RG' => 'Régimen general',
        'FD' => 'Fijos/as discontinuos/as en períodos de no ocupación',
        'RE' => 'Regulación de empleo en periodos de no ocupación',
        'AGP' => 'Régimen especial agrario por cuenta propia',
        'AGA' => 'Régimen especial agrario por cuenta ajena',
        'AU' => 'Régimen especial autónomos/as',
        'EH' => 'Empleado/a hogar',
        'DF' => 'Trabajadores/as que accedan al desempleo durante el período formativo',
        'RLE' => 'Trabajadores/as con relaciones laborales de carácter especial (art. 2 del Estatuto de los Trabajadores/as)',
        'CESS' => 'Trabajadores/as con convenio especial con la Seguridad Social',
        'FDI' => 'Trabajadores/as a tiempo parcial indefinido (con trabajos discontinuos) en períodos de no ocupación',
        'TM' => 'Trabajadores/as incluidos en el régimen especial del mar',
        'CP' => 'Mutualistas de Colegios Profesionales no incluidos como autónomos/as',
    ],

    'via' => [
        'Calle',
        'Avenida',
        'Plaza',
        'Paseo',
        'Carretera',
        'Camino',
        'Ronda',
        'Travesía',
        'Barrio',
        'Urbanización',
        'Parque'
    ],

    'nivel_academico' => [
        'sin_estudios' => 'Sin estudios',
        'estudios_primarios' => 'Estudios primarios',
        'certificado_escolaridad' => 'Certificado de escolaridad',
        'graduado_escolar' => 'Graduado escolar',
        'eso' => 'ESO',
        'fp1' => 'FP I',
        'ciclo_grado_medio' => 'Ciclo grado medio',
        'bup_1_2' => 'BUP 1-2',
        'bup_1_2_3' => 'BUP 1-3',
        'fp2' => 'FP II',
        'ciclo_grado_superior' => 'Ciclo grado superior',
        'cou' => 'COU',
        'bachiller' => 'Bachiller',
        'diplomatura' => 'Diplomatura',
        'licenciatura' => 'Licenciatura',
        'grado' => 'Grado',
        'doctorado' => 'Doctorado',
        'certificado_profesional_n1' => 'Certificado profesional N1',
        'certificado_profesional_n2' => 'Certificado profesional N2',
        'certificado_profesional_n3' => 'Certificado profesional N3',
        'otros' => 'Otros',
    ],


];
